### ISSUE TITLE
Develop bare bones of web app

### ISSUE THREAD

**Issue by IohannesArnold** [getmovement/national-voter-file#25]
I understand that, in principle, this project is about data collection and management, not creating software. If/when this project gets off the ground, scores of web developers will swoop in to use our data for their own web apps, hence there is no formal need for a web app associated with the national-voter-file project: we are creating a database that will power many apps, not just one.

However, as someone who is not all that experienced in working with databases, this feels alien to me. I want to ask "where is the website?" -- to type in nationalvoterfile.org and get served _something_, not just redirected to Github. And I suspect I am not alone in my impulses, at least among possible ChiHackNight volunteers. So I think it would make this project more relatable if we could at least serve a static HTML page with a colored in map, and maybe the basics of an API (even if it's extremely basic and effectively useless compared to direct querying of the database). That would make the project more cognizable to me, and, I think many people.

I plan on doing this myself after I get the newbie onboarding moving along, but thought I'd post now as a heads up and to get others' thoughts.

**Comment by JoshSmith** [comment]
@IohannesArnold absolutely will do, it's just been on the backburner relative to other things for the time being. (Other things being standing up Code Corps).

We're likely to interact with said database via an Elixir API, but if we could have even just an _informational_ landing page served up at first by an Elixir/Phoenix app, that would be my ideal scenario.

**Comment by slavingia** [comment]
Hi - I talked to Ben and am thinking about putting together a mini website (with a big Go To Github button, still) with some context to what we do and why we exist.

**Comment by JoshSmith** [comment]
@slavingia yep, this sounds great. What are you thinking here?

I was hoping for something along the lines of:

- Blurb about the project and end goals
- Map that displays current progress
- List of states
- Context about the cost of each state's file
- Link to GitHub to contribute

Obviously would love to ship something smaller sooner to at least get something up.

We could use something like http://intridea.github.io/stately/ to quickly throw such a map together.

The content can even be really static early on.

**Comment by slavingia** [comment]
yep, basically that. a micro marketing website with a "check us out on GitHub" button. just so people understand the value of what we're building, and how a future looks like with it existing and being used

**Comment by slavingia** [comment]
i've posted a design in slack

**Comment by slavingia** [comment]
[
![pasted image at 2016_11_20 05_14 pm](https://cloud.githubusercontent.com/assets/74396/20471126/e7c31332-af63-11e6-843b-465a4d6f9828.png)
](url)

**Comment by JoshSmith** [comment]
Excited to see this.

**Comment by JoeNVF** [comment]
Maybe mention (or even just link to the wikipedia page) about the competition.

For many the concept of a voter database doesn't mean much, so explain a bit about what is currently out there and how it is used.

**Comment by slavingia** [comment]
which competition? happy to.

btw, opened a PR for `national-voter-file-website` for the ultra-bare bones version. no map, no donate link, no twitter link

**Comment by slavingia** [comment]
added a map and another link to spice it up. donate + twitter pending.

**Comment by JoeNVF** [comment]
RNC uses Voter Vault DNC had Demzilla but I think they moved to NGP VAN now.  Both are voter files, like what we are building, but controlled by the parties.  Don't play by their rules (for example, primarying an incumbent) and they could refuse you access.

**Comment by slavingia** [comment]
got it! thanks

**Comment by JoeNVF** [comment]
Should we add a link to the dimensional model to the site?  Right now it's a nice and quick display of the basic concept, but IMO offering more detail (which that document does) shows a level of seriousness in the project.

https://docs.google.com/document/d/169mIkiIdl4OetbGvnbVCzq9Srw9PKCsB6U1CErTD9aI/

Just a thought.
