### ISSUE TITLE
docker-compose build fails when installed from apt

### ISSUE THREAD

**Issue by hibes** [getmovement/national-voter-file#29]
```
$ docker-compose build
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

This can be fixed by pulling down the docker-compose binary from https://docs.docker.com/compose/install/.

**Comment by JoshSmith** [comment]
@hibes sorry, just a little bit confused by the issue you're having. Are you saying that you got this error and resolved it yourself by getting the latest `docker-compose`?

What action would you like to see taken here?

**Comment by hibes** [comment]
I was going to use this to track my change, but then I realized I didn't have permissions to push.

**Comment by BenGalewsky** [comment]
He just wants to clarify the instructions. His ubuntu build had an old docker-compose that wasn't compatible with my docker-compose.yml

**Comment by JoshSmith** [comment]
Got it; do we need to update README then to clarify?

**Comment by hibes** [comment]
Yeah, I have a branch ready to push and request a PR once I have access.

**Comment by JoshSmith** [comment]
@hibes I think I asked elsewhere, but why don't you fork and push there?

**Comment by hibes** [comment]
I can do that when I get home.  I am under the impression that you can't merge between forks, but that sounds silly as I type it out.

**Comment by JoshSmith** [comment]
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by hibes** [comment]
Resolved with the addition of the comment.
