### ISSUE TITLE
Create process to load congressional district dimension

### ISSUE THREAD

**Issue by BenGalewsky** [getmovement/national-voter-file#33]
The congressional_dist_dim is populated with data downloaded from [censusreporter.](https://github.com/censusreporter/census-api)

The process is driven by FIPS codes found in:
https://www.census.gov/geo/reference/codes/cd113.html

The python script src\main\python\censusreporter\createCongressionalDists.py reads this file and uses the FIPS code to look up data from a number of AFS tables and then writes the enriched data out to a CSV file which is loaded into the DB with the Kettle transform src\main\pdi\LoadCongressionalDistsDim.ktr

I did this process for New York state. We need to either load all of the US in, or at least make it easy to do on a state-by-state basis

**Comment by JoeNVF** [comment]
Working on this.
