### ISSUE TITLE
Create Process to load County Dimension

### ISSUE THREAD

**Issue by BenGalewsky** [getmovement/national-voter-file#34]
The county_dim is populated with data downloaded from [censusreporter.](https://github.com/censusreporter/census-api)

The process is driven by FIPS codes found in:
https://www.census.gov/geo/reference/codes/cou.html

The python script src\main\python\censusreporter\createCounties.py reads this file and uses the FIPS code to look up data from a number of AFS tables and then writes the enriched data out to a CSV file which is loaded into the DB with the Kettle transform src\main\pdi\LoadCountyDim.ktr

I did this process for New York state. We need to  make it easy to do on a state-by-state basis. It should be easy to lookup counties from each state's voter file county code lookup code

**Comment by JoeNVF** [comment]
Working on this.  Issue noted with C7 counties, which are independent cities, Virginia county# 515 has no census data.  Need to test to see if census lacks data on all C7's (if so, we'll have to exclude them so the script doesn't crap out) or if this is an isolated issue.
