### ISSUE TITLE
Load state upper and lower house district dimensions

### ISSUE THREAD

**Issue by BenGalewsky** [getmovement/national-voter-file#36]
The upper and lower house dimensions are populated with data downloaded from [censusreporter.](https://github.com/censusreporter/census-api)

The process is driven by FIPS codes found in:
https://www.census.gov/geo/maps-data/data/gazetteer2016.html

The python script src\main\python\censusreporter\lowerHouseDists.py and upperHouseDists.py read these files and uses the FIPS code to look up data from a number of AFS tables and then writes the enriched data out to a CSV file which is loaded into the DB with the Kettle transform src\main\pdi\LoadLowerHouseDim.ktr and LoadUpperHouseDim.ktr

I did this process for New York state. We need to load all of the US or at least make it easy to do on a state-by-state basis.

**Comment by JoeNVF** [comment]
Working on this.
