### ISSUE TITLE
Update the project's README

### ISSUE THREAD

**Issue by slavingia** [getmovement/national-voter-file#42]
I'm going to clean up this once my other changes are accepted/rejected into `master`, to make sure I am headed in the right direction.

Once the README is cleaned up, that'll give us a good, text-based direction to build the mini-site off of.

**Comment by slavingia** [comment]
Made a few tweaks to the bottom bits. Will do the big rewrite next.

**Comment by slavingia** [comment]
Opened a PR for the main content rewrite, inspired by the old "newcomers" branch I found :)

I will move the architecture bits to the SQL README next, and have two sections in the main readme:

learn more

and

how to contribute

**Comment by JoshSmith** [comment]
@slavingia in your "how to contribute" section, if you could primarily link to `.github/CONTRIBUTING.md` to conform to GitHub conventions, that would be great.

Something along the lines of https://github.com/code-corps/code-corps-api#how-can-i-help

**Comment by slavingia** [comment]
good idea, i'll create another issue for that.
