### ISSUE TITLE
Seek out and Order State Voter Files

### ISSUE THREAD

**Issue by BenGalewsky** [getmovement/national-voter-file#58]
We need to keep the pipeline of voter files filled for on-going development. 

Use resources like:
- http://voterlist.electproject.org/
- https://github.com/pablobarbera/voter-files
- https://drive.google.com/open?id=1CtNePb4LQSz-pk8UF58wwuVoBIc_YDAsBJZnIk7hKso

to find low-cost voter files. Some of them require filling out a form and FAXing(!) to the Secretary of State. Once you have the file and the data dictionary it should be uploaded to drop box.

Add comments to this ticket to indicate a state that is in flight.

**Comment by slavingia** [comment]
I think we need a slightly better solution than comments to track. I don't think people will find it very intuitive. I'll think on this. Ideas appreciated.

(Something like a public Trello w/ a pipeline people can follow per state or somesuch.)

**Comment by JoshSmith** [comment]
Public Trello seems ideal. Or Airtable. Or Google Sheets.

**Comment by slavingia** [comment]
k i'll go with that

**Comment by slavingia** [comment]
started on https://trello.com/b/IlZkwYc0

**Comment by JoshSmith** [comment]
@slavingia maybe missed it but is this listed in README now?

**Comment by slavingia** [comment]
Yep, here:
https://github.com/getmovement/national-voter-file/pull/61#discussion-diff-90792087R23
